
[[gkom.object]]
model = "cube"
position = [1.0, 1.0, 1.0]
rotation = [20.0, 60.0, 0.0]
scale = [2.0, 1.0, 0.5]
color = [1.0, 0.6, 0.8]
shininess = 4

[[gkom.object]]
model = "cube"
position = [4.0, 8.0, 8.0]
rotation = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]
color = [1.0, 0.6, 0.8]
shininess = 8

[[gkom.object]]
model = "cube"
position = [-4.0, -8.0, 8.0]
rotation = [0.0, 0.0, 0.0]
scale = [2.0, 2.0, 2.0]
color = [1.0, 0.6, 0.8]
shininess = 16

[[gkom.object]]
model = "cube"
position = [16.0, 16.0, 16.0]
rotation = [0.0, 0.0, 0.0]
scale = [2.0, 2.0, 2.0]
color = [1.0, 0.6, 0.8]
shininess = 32



[[gkom.light]]
type = "point"
position = [8.0, 8.0, 8.0]
diffuse = [1.0, 0.0, 0.0]
specular = [1.0, 0.0, 0.0]

[[gkom.light]]
type = "point"
position = [-8.0, -8.0, 8.0]
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]
