[[gkom.object]]
model = "cube"
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]
color = [0.0, 0.5, 0.5]

[[gkom.light]]
type = "point"
position = [0.0, 0.0, 0.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
