
[[gkom.object]]
model = "cube"
position = [1.0, 1.0, 1.0]
rotation = [20.0, 60.0, 0.0]
scale = [1.0, 1.0, 1.0]
color = [1.0, 0.6, 0.8]
shininess = 1

[[gkom.light]]
type = "point"
position = [0.0, 0.0, 0.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
